..\Phalanger\Source\PhpNetCompiler\obj\Debug)\phpc ^
/target:dll ^
/pure+ ^
/lang:CLR ^
/out:WikiLingo.dll ^
/recurse:../wikiLingo\WikiLingo ^
/recurse:../wikiLingo\WikiLingoWYSIWYG ^
/recurse:../wikiLingo\WYSIWYGWikiLingo ^
/recurse:../wikiLingo\Types ^
/r:../Phalanger\Source\ClassLibrary\obj\Debug)\PhpNetClassLibrary.dll 2>out.log